# Generated by Django 5.2.8 on 2025-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_number',
            field=models.CharField(default='00000000000', help_text='e.g., 923001234567', max_length=15),
            preserve_default=False,
        ),
    ]
